import type { ConfigSchema } from '@/lib/config-schema'

export type ComponentKind = 'trigger' | 'ai' | 'knowledge' | 'logic' | 'trust' | 'transform' | 'connection' | 'output'

export interface ComponentPort {
  id: string
  name: string
  type: string
  required?: boolean
  description?: string
}

export interface ComponentGroup {
  id: string
  name: string
  icon: string
  description: string
  color: string
  gradient: string
  sortOrder: number
}

export interface ComponentDefinition {
  id: string
  name: string
  displayName: string
  version: string
  kind: ComponentKind
  category: string
  description: string
  inputs: ComponentPort[]
  outputs: ComponentPort[]
  hasAI: boolean
  aiToggles?: string[]
  color: string
  icon: string
  tags?: string[]
  configSchema?: ConfigSchema
}

// ============================================================
// 8 Universal Component Groups
// ============================================================
export const componentGroups: ComponentGroup[] = [
  {
    id: 'triggers',
    name: 'Triggers & Inputs',
    icon: 'Zap',
    description: 'Start agent execution from events, messages, or schedules',
    color: 'emerald',
    gradient: 'from-emerald-500 to-green-500',
    sortOrder: 1,
  },
  {
    id: 'ai-models',
    name: 'AI & Models',
    icon: 'Sparkles',
    description: 'Large language models, classifiers, and AI capabilities',
    color: 'purple',
    gradient: 'from-purple-500 to-pink-500',
    sortOrder: 2,
  },
  {
    id: 'knowledge',
    name: 'Knowledge & Memory',
    icon: 'Database',
    description: 'Knowledge bases, vector stores, and conversation memory',
    color: 'blue',
    gradient: 'from-blue-500 to-cyan-500',
    sortOrder: 3,
  },
  {
    id: 'logic',
    name: 'Logic & Flow',
    icon: 'GitBranch',
    description: 'Conditional routing, loops, and flow control',
    color: 'amber',
    gradient: 'from-amber-500 to-orange-500',
    sortOrder: 4,
  },
  {
    id: 'trust',
    name: 'Trust & Governance',
    icon: 'ShieldCheck',
    description: 'Human approvals, guardrails, policy enforcement, and attestation',
    color: 'rose',
    gradient: 'from-rose-500 to-red-500',
    sortOrder: 5,
  },
  {
    id: 'data',
    name: 'Data & Transform',
    icon: 'Settings',
    description: 'Variables, code execution, data parsing, and transformations',
    color: 'indigo',
    gradient: 'from-indigo-500 to-violet-500',
    sortOrder: 6,
  },
  {
    id: 'connections',
    name: 'Connections',
    icon: 'Globe',
    description: 'HTTP, databases, email, Slack, and external integrations',
    color: 'green',
    gradient: 'from-green-500 to-emerald-500',
    sortOrder: 7,
  },
  {
    id: 'outputs',
    name: 'Outputs & Responses',
    icon: 'MessageCircle',
    description: 'Chat responses, API replies, notifications, and endpoints',
    color: 'slate',
    gradient: 'from-slate-500 to-gray-500',
    sortOrder: 8,
  },
]

// Keep backward-compat alias used by Studio palette
export const componentCategories = componentGroups

// ============================================================
// 55 Universal Components
// ============================================================
export const mockComponents: ComponentDefinition[] = [
  // ==================== TRIGGERS & INPUTS (7) ====================
  {
    id: 'trigger.ChatMessage',
    name: 'trigger.ChatMessage',
    displayName: 'Chat Message',
    version: '1.0.0',
    kind: 'trigger',
    category: 'triggers',
    description: 'Triggered when a user sends a chat message',
    inputs: [],
    outputs: [
      { id: 'message', name: 'message', type: 'string', description: 'The user message text' },
      { id: 'user_id', name: 'user_id', type: 'string', description: 'Sender identifier' },
      { id: 'session_id', name: 'session_id', type: 'string', description: 'Conversation session' },
    ],
    hasAI: false,
    color: 'emerald',
    icon: 'MessageSquare',
    tags: ['chat', 'message', 'input'],
  },
  {
    id: 'trigger.Webhook',
    name: 'trigger.Webhook',
    displayName: 'Webhook',
    version: '1.0.0',
    kind: 'trigger',
    category: 'triggers',
    description: 'Triggered by an incoming HTTP webhook request',
    inputs: [],
    outputs: [
      { id: 'body', name: 'body', type: 'object', description: 'Request body' },
      { id: 'headers', name: 'headers', type: 'object', description: 'Request headers' },
      { id: 'method', name: 'method', type: 'string', description: 'HTTP method' },
    ],
    hasAI: false,
    color: 'emerald',
    icon: 'Webhook',
    tags: ['webhook', 'http', 'api'],
    configSchema: {
      groups: [
        { key: 'endpoint', label: 'Endpoint', order: 1 },
        { key: 'auth', label: 'Authentication', order: 2 },
      ],
      fields: [
        { key: 'path', type: 'string', label: 'Path', required: true, defaultValue: '/webhook',
          placeholder: '/my-webhook', group: 'endpoint' },
        { key: 'method', type: 'select', label: 'HTTP Method', defaultValue: 'POST',
          options: [
            { label: 'POST', value: 'POST' },
            { label: 'GET', value: 'GET' },
            { label: 'PUT', value: 'PUT' },
          ], group: 'endpoint' },
        { key: 'auth_type', type: 'select', label: 'Auth Type', defaultValue: 'none',
          options: [
            { label: 'None', value: 'none' },
            { label: 'API Key', value: 'api_key' },
            { label: 'HMAC Signature', value: 'hmac' },
          ], group: 'auth' },
        { key: 'auth_header', type: 'string', label: 'Header Name', defaultValue: 'X-API-Key',
          placeholder: 'X-API-Key',
          visibleWhen: [{ field: 'auth_type', value: 'api_key' }], group: 'auth' },
        { key: 'auth_secret', type: 'secret', label: 'Secret',
          placeholder: 'Enter secret...',
          visibleWhen: [{ field: 'auth_type', value: ['api_key', 'hmac'] }], group: 'auth' },
        { key: 'hmac_algorithm', type: 'select', label: 'HMAC Algorithm', defaultValue: 'sha256',
          options: [
            { label: 'SHA-256', value: 'sha256' },
            { label: 'SHA-1', value: 'sha1' },
          ],
          visibleWhen: [{ field: 'auth_type', value: 'hmac' }], group: 'auth' },
      ],
    },
  },
  {
    id: 'trigger.Schedule',
    name: 'trigger.Schedule',
    displayName: 'Schedule',
    version: '1.0.0',
    kind: 'trigger',
    category: 'triggers',
    description: 'Triggered on a cron schedule or interval',
    inputs: [],
    outputs: [
      { id: 'timestamp', name: 'timestamp', type: 'datetime', description: 'Trigger time' },
      { id: 'run_id', name: 'run_id', type: 'string', description: 'Unique run identifier' },
    ],
    hasAI: false,
    color: 'emerald',
    icon: 'Clock',
    tags: ['schedule', 'cron', 'timer'],
  },
  {
    id: 'trigger.EmailReceived',
    name: 'trigger.EmailReceived',
    displayName: 'Email Received',
    version: '1.0.0',
    kind: 'trigger',
    category: 'triggers',
    description: 'Triggered when an email is received at a monitored inbox',
    inputs: [],
    outputs: [
      { id: 'from', name: 'from', type: 'string', description: 'Sender address' },
      { id: 'subject', name: 'subject', type: 'string', description: 'Email subject' },
      { id: 'body', name: 'body', type: 'string', description: 'Email body' },
      { id: 'attachments', name: 'attachments', type: 'File[]', description: 'Attached files' },
    ],
    hasAI: false,
    color: 'emerald',
    icon: 'MailOpen',
    tags: ['email', 'inbox', 'message'],
  },
  {
    id: 'trigger.APICall',
    name: 'trigger.APICall',
    displayName: 'API Call',
    version: '1.0.0',
    kind: 'trigger',
    category: 'triggers',
    description: 'Triggered by an authenticated API request to a custom endpoint',
    inputs: [],
    outputs: [
      { id: 'params', name: 'params', type: 'object', description: 'Request parameters' },
      { id: 'body', name: 'body', type: 'object', description: 'Request body' },
      { id: 'auth', name: 'auth', type: 'object', description: 'Auth context' },
    ],
    hasAI: false,
    color: 'emerald',
    icon: 'PlugZap',
    tags: ['api', 'endpoint', 'rest'],
  },
  {
    id: 'trigger.FileUpload',
    name: 'trigger.FileUpload',
    displayName: 'File Upload',
    version: '1.0.0',
    kind: 'trigger',
    category: 'triggers',
    description: 'Triggered when a file is uploaded by a user or system',
    inputs: [],
    outputs: [
      { id: 'file', name: 'file', type: 'File', description: 'The uploaded file' },
      { id: 'filename', name: 'filename', type: 'string', description: 'Original filename' },
      { id: 'mime_type', name: 'mime_type', type: 'string', description: 'MIME type' },
    ],
    hasAI: false,
    color: 'emerald',
    icon: 'Upload',
    tags: ['file', 'upload', 'document'],
  },
  {
    id: 'trigger.FormSubmission',
    name: 'trigger.FormSubmission',
    displayName: 'Form Submission',
    version: '1.0.0',
    kind: 'trigger',
    category: 'triggers',
    description: 'Triggered when a user submits a form',
    inputs: [],
    outputs: [
      { id: 'fields', name: 'fields', type: 'object', description: 'Form field values' },
      { id: 'form_id', name: 'form_id', type: 'string', description: 'Form identifier' },
      { id: 'user_id', name: 'user_id', type: 'string', description: 'Submitter' },
    ],
    hasAI: false,
    color: 'emerald',
    icon: 'FormInput',
    tags: ['form', 'submit', 'input'],
  },

  // ==================== AI & MODELS (8) ====================
  {
    id: 'ai.LLM',
    name: 'ai.LLM',
    displayName: 'LLM',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Send a prompt to a large language model and receive a completion',
    inputs: [
      { id: 'prompt', name: 'prompt', type: 'string', required: true, description: 'The prompt or messages' },
      { id: 'system', name: 'system', type: 'string', description: 'System prompt' },
      { id: 'context', name: 'context', type: 'string', description: 'Additional context' },
    ],
    outputs: [
      { id: 'response', name: 'response', type: 'string', description: 'Model response text' },
      { id: 'tokens_used', name: 'tokens_used', type: 'number', description: 'Token count' },
    ],
    hasAI: true,
    aiToggles: ['model_selection', 'temperature', 'max_tokens'],
    color: 'purple',
    icon: 'Brain',
    tags: ['llm', 'gpt', 'claude', 'completion'],
    configSchema: {
      groups: [
        { key: 'provider', label: 'Provider & Model', order: 1 },
        { key: 'prompts', label: 'Prompts', order: 2 },
        { key: 'parameters', label: 'Model Parameters', order: 3 },
        { key: 'advanced', label: 'Advanced', order: 4, collapsible: true, defaultCollapsed: true },
      ],
      fields: [
        { key: 'provider', type: 'select', label: 'Provider', required: true, defaultValue: 'anthropic',
          options: [
            { label: 'Anthropic', value: 'anthropic' },
            { label: 'OpenAI', value: 'openai' },
            { label: 'Google', value: 'google' },
          ], group: 'provider' },
        { key: 'model', type: 'select', label: 'Model', required: true, defaultValue: 'claude-sonnet-4-5-20250929',
          options: [
            { label: 'Claude Sonnet 4.5', value: 'claude-sonnet-4-5-20250929' },
            { label: 'Claude Opus 4', value: 'claude-opus-4-20250514' },
          ],
          visibleWhen: [{ field: 'provider', value: 'anthropic' }], group: 'provider' },
        { key: 'model', type: 'select', label: 'Model', required: true, defaultValue: 'gpt-4o',
          options: [
            { label: 'GPT-4o', value: 'gpt-4o' },
            { label: 'GPT-4o mini', value: 'gpt-4o-mini' },
          ],
          visibleWhen: [{ field: 'provider', value: 'openai' }], group: 'provider' },
        { key: 'model', type: 'select', label: 'Model', required: true, defaultValue: 'gemini-2.5-pro',
          options: [
            { label: 'Gemini 2.5 Pro', value: 'gemini-2.5-pro' },
            { label: 'Gemini 2.5 Flash', value: 'gemini-2.5-flash' },
          ],
          visibleWhen: [{ field: 'provider', value: 'google' }], group: 'provider' },
        { key: 'api_key', type: 'secret', label: 'API Key',
          description: 'Leave blank to use workspace default.', placeholder: 'sk-...', group: 'provider' },
        { key: 'system_prompt', type: 'textarea', label: 'System Prompt',
          placeholder: 'You are a helpful assistant...', group: 'prompts' },
        { key: 'temperature', type: 'slider', label: 'Temperature',
          description: 'Lower = more deterministic', defaultValue: 0.7, step: 0.1,
          validation: { min: 0, max: 2 }, group: 'parameters' },
        { key: 'max_tokens', type: 'number', label: 'Max Tokens', defaultValue: 1024,
          validation: { min: 1, max: 128000 }, group: 'parameters' },
        { key: 'streaming', type: 'boolean', label: 'Stream Response', defaultValue: false, group: 'advanced' },
        { key: 'stop_sequences', type: 'string-array', label: 'Stop Sequences',
          validation: { maxItems: 4 }, group: 'advanced' },
      ],
    },
  },
  {
    id: 'ai.Classifier',
    name: 'ai.Classifier',
    displayName: 'Classifier',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Classify input text into predefined categories using AI',
    inputs: [
      { id: 'text', name: 'text', type: 'string', required: true, description: 'Text to classify' },
      { id: 'categories', name: 'categories', type: 'string[]', required: true, description: 'Category labels' },
    ],
    outputs: [
      { id: 'category', name: 'category', type: 'string', description: 'Best matching category' },
      { id: 'confidence', name: 'confidence', type: 'number', description: 'Confidence score 0-1' },
      { id: 'scores', name: 'scores', type: 'object', description: 'All category scores' },
    ],
    hasAI: true,
    aiToggles: ['model_selection', 'threshold'],
    color: 'purple',
    icon: 'Tags',
    tags: ['classify', 'intent', 'category'],
    configSchema: {
      groups: [
        { key: 'model', label: 'Model', order: 1 },
        { key: 'classification', label: 'Classification', order: 2 },
      ],
      fields: [
        { key: 'provider', type: 'select', label: 'Provider', defaultValue: 'anthropic',
          options: [
            { label: 'Anthropic', value: 'anthropic' },
            { label: 'OpenAI', value: 'openai' },
          ], group: 'model' },
        { key: 'categories', type: 'string-array', label: 'Categories', required: true,
          placeholder: 'Enter category name...', defaultValue: ['positive', 'negative', 'neutral'],
          validation: { minItems: 2, maxItems: 20 }, group: 'classification' },
        { key: 'confidence_threshold', type: 'slider', label: 'Confidence Threshold',
          description: 'Minimum confidence to accept classification', defaultValue: 0.7, step: 0.05,
          validation: { min: 0, max: 1 }, group: 'classification' },
        { key: 'multi_label', type: 'boolean', label: 'Multi-label', defaultValue: false,
          description: 'Allow multiple categories per input', group: 'classification' },
      ],
    },
  },
  {
    id: 'ai.PromptTemplate',
    name: 'ai.PromptTemplate',
    displayName: 'Prompt Template',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Build a prompt from a template with variable substitution',
    inputs: [
      { id: 'template', name: 'template', type: 'string', required: true, description: 'Template with {{variables}}' },
      { id: 'variables', name: 'variables', type: 'object', required: true, description: 'Variable values' },
    ],
    outputs: [
      { id: 'prompt', name: 'prompt', type: 'string', description: 'Rendered prompt' },
    ],
    hasAI: false,
    color: 'purple',
    icon: 'FileCode',
    tags: ['prompt', 'template', 'variables'],
  },
  {
    id: 'ai.Embeddings',
    name: 'ai.Embeddings',
    displayName: 'Embeddings',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Generate vector embeddings from text for semantic search',
    inputs: [
      { id: 'text', name: 'text', type: 'string', required: true, description: 'Text to embed' },
    ],
    outputs: [
      { id: 'vector', name: 'vector', type: 'number[]', description: 'Embedding vector' },
      { id: 'dimensions', name: 'dimensions', type: 'number', description: 'Vector dimensions' },
    ],
    hasAI: true,
    aiToggles: ['model_selection'],
    color: 'purple',
    icon: 'Binary',
    tags: ['embedding', 'vector', 'semantic'],
  },
  {
    id: 'ai.SpeechToText',
    name: 'ai.SpeechToText',
    displayName: 'Speech to Text',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Transcribe audio input to text using AI',
    inputs: [
      { id: 'audio', name: 'audio', type: 'File', required: true, description: 'Audio file or stream' },
      { id: 'language', name: 'language', type: 'string', description: 'Language hint' },
    ],
    outputs: [
      { id: 'text', name: 'text', type: 'string', description: 'Transcribed text' },
      { id: 'confidence', name: 'confidence', type: 'number', description: 'Transcription confidence' },
    ],
    hasAI: true,
    aiToggles: ['model_selection', 'language'],
    color: 'purple',
    icon: 'Mic',
    tags: ['speech', 'audio', 'transcribe', 'stt'],
  },
  {
    id: 'ai.TextToSpeech',
    name: 'ai.TextToSpeech',
    displayName: 'Text to Speech',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Convert text to natural-sounding speech audio',
    inputs: [
      { id: 'text', name: 'text', type: 'string', required: true, description: 'Text to speak' },
      { id: 'voice', name: 'voice', type: 'string', description: 'Voice preset' },
    ],
    outputs: [
      { id: 'audio', name: 'audio', type: 'File', description: 'Generated audio file' },
      { id: 'duration', name: 'duration', type: 'number', description: 'Duration in seconds' },
    ],
    hasAI: true,
    aiToggles: ['model_selection', 'voice'],
    color: 'purple',
    icon: 'Volume2',
    tags: ['speech', 'audio', 'tts', 'voice'],
  },
  {
    id: 'ai.Vision',
    name: 'ai.Vision',
    displayName: 'Vision',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Analyze images using AI vision models',
    inputs: [
      { id: 'image', name: 'image', type: 'File', required: true, description: 'Image to analyze' },
      { id: 'prompt', name: 'prompt', type: 'string', description: 'Analysis prompt' },
    ],
    outputs: [
      { id: 'description', name: 'description', type: 'string', description: 'Image analysis result' },
      { id: 'objects', name: 'objects', type: 'object[]', description: 'Detected objects' },
    ],
    hasAI: true,
    aiToggles: ['model_selection'],
    color: 'purple',
    icon: 'Eye',
    tags: ['vision', 'image', 'ocr', 'analyze'],
  },
  {
    id: 'ai.AgentToolUse',
    name: 'ai.AgentToolUse',
    displayName: 'Agent Tool Use',
    version: '1.0.0',
    kind: 'ai',
    category: 'ai-models',
    description: 'Let an AI agent autonomously select and use tools to complete a task',
    inputs: [
      { id: 'task', name: 'task', type: 'string', required: true, description: 'Task description' },
      { id: 'tools', name: 'tools', type: 'string[]', required: true, description: 'Available tool IDs' },
      { id: 'context', name: 'context', type: 'string', description: 'Additional context' },
    ],
    outputs: [
      { id: 'result', name: 'result', type: 'any', description: 'Agent result' },
      { id: 'tool_calls', name: 'tool_calls', type: 'object[]', description: 'Tools used' },
      { id: 'reasoning', name: 'reasoning', type: 'string', description: 'Agent reasoning trace' },
    ],
    hasAI: true,
    aiToggles: ['model_selection', 'max_iterations', 'tool_permissions'],
    color: 'purple',
    icon: 'Bot',
    tags: ['agent', 'tool', 'autonomous', 'agentic'],
  },

  // ==================== KNOWLEDGE & MEMORY (6) ====================
  {
    id: 'knowledge.KnowledgeBase',
    name: 'knowledge.KnowledgeBase',
    displayName: 'Knowledge Base',
    version: '1.0.0',
    kind: 'knowledge',
    category: 'knowledge',
    description: 'Search a knowledge base using semantic similarity (RAG)',
    inputs: [
      { id: 'query', name: 'query', type: 'string', required: true, description: 'Search query' },
      { id: 'top_k', name: 'top_k', type: 'number', description: 'Number of results' },
    ],
    outputs: [
      { id: 'results', name: 'results', type: 'object[]', description: 'Matching documents' },
      { id: 'context', name: 'context', type: 'string', description: 'Concatenated context text' },
    ],
    hasAI: true,
    aiToggles: ['embedding_model', 'similarity_threshold'],
    color: 'blue',
    icon: 'BookOpen',
    tags: ['rag', 'search', 'knowledge', 'retrieval'],
  },
  {
    id: 'knowledge.DocumentLoader',
    name: 'knowledge.DocumentLoader',
    displayName: 'Document Loader',
    version: '1.0.0',
    kind: 'knowledge',
    category: 'knowledge',
    description: 'Load and parse documents (PDF, DOCX, TXT, HTML) into chunks',
    inputs: [
      { id: 'file', name: 'file', type: 'File', required: true, description: 'Document file' },
      { id: 'chunk_size', name: 'chunk_size', type: 'number', description: 'Chunk size in tokens' },
    ],
    outputs: [
      { id: 'chunks', name: 'chunks', type: 'string[]', description: 'Document chunks' },
      { id: 'metadata', name: 'metadata', type: 'object', description: 'Document metadata' },
    ],
    hasAI: false,
    color: 'blue',
    icon: 'FileText',
    tags: ['document', 'parse', 'chunk', 'loader'],
  },
  {
    id: 'knowledge.VectorStore',
    name: 'knowledge.VectorStore',
    displayName: 'Vector Store',
    version: '1.0.0',
    kind: 'knowledge',
    category: 'knowledge',
    description: 'Store and query vector embeddings for semantic search',
    inputs: [
      { id: 'operation', name: 'operation', type: 'string', required: true, description: '"upsert" or "query"' },
      { id: 'vectors', name: 'vectors', type: 'any', description: 'Vectors to store or query vector' },
    ],
    outputs: [
      { id: 'results', name: 'results', type: 'object[]', description: 'Query results' },
      { id: 'count', name: 'count', type: 'number', description: 'Items affected' },
    ],
    hasAI: false,
    color: 'blue',
    icon: 'Database',
    tags: ['vector', 'store', 'embeddings', 'index'],
  },
  {
    id: 'knowledge.ConversationMemory',
    name: 'knowledge.ConversationMemory',
    displayName: 'Conversation Memory',
    version: '1.0.0',
    kind: 'knowledge',
    category: 'knowledge',
    description: 'Store and retrieve conversation history for context',
    inputs: [
      { id: 'session_id', name: 'session_id', type: 'string', required: true, description: 'Session identifier' },
      { id: 'message', name: 'message', type: 'object', description: 'Message to store' },
    ],
    outputs: [
      { id: 'history', name: 'history', type: 'object[]', description: 'Conversation messages' },
      { id: 'summary', name: 'summary', type: 'string', description: 'Conversation summary' },
    ],
    hasAI: false,
    color: 'blue',
    icon: 'History',
    tags: ['memory', 'conversation', 'history', 'context'],
  },
  {
    id: 'knowledge.SessionState',
    name: 'knowledge.SessionState',
    displayName: 'Session State',
    version: '1.0.0',
    kind: 'knowledge',
    category: 'knowledge',
    description: 'Get or set key-value state for the current session',
    inputs: [
      { id: 'key', name: 'key', type: 'string', required: true, description: 'State key' },
      { id: 'value', name: 'value', type: 'any', description: 'Value to set (omit to get)' },
    ],
    outputs: [
      { id: 'value', name: 'value', type: 'any', description: 'Current value' },
    ],
    hasAI: false,
    color: 'blue',
    icon: 'HardDrive',
    tags: ['state', 'session', 'key-value'],
  },
  {
    id: 'knowledge.Cache',
    name: 'knowledge.Cache',
    displayName: 'Cache',
    version: '1.0.0',
    kind: 'knowledge',
    category: 'knowledge',
    description: 'Cache responses to avoid redundant computation or API calls',
    inputs: [
      { id: 'key', name: 'key', type: 'string', required: true, description: 'Cache key' },
      { id: 'value', name: 'value', type: 'any', description: 'Value to cache' },
      { id: 'ttl', name: 'ttl', type: 'number', description: 'Time-to-live in seconds' },
    ],
    outputs: [
      { id: 'value', name: 'value', type: 'any', description: 'Cached value' },
      { id: 'hit', name: 'hit', type: 'boolean', description: 'Whether cache was hit' },
    ],
    hasAI: false,
    color: 'blue',
    icon: 'Archive',
    tags: ['cache', 'memoize', 'ttl'],
  },

  // ==================== LOGIC & FLOW (7) ====================
  {
    id: 'logic.Condition',
    name: 'logic.Condition',
    displayName: 'Condition',
    version: '1.0.0',
    kind: 'logic',
    category: 'logic',
    description: 'Route the workflow based on a boolean condition',
    inputs: [
      { id: 'value', name: 'value', type: 'any', required: true, description: 'Value to evaluate' },
      { id: 'condition', name: 'condition', type: 'string', required: true, description: 'Expression to evaluate' },
    ],
    outputs: [
      { id: 'true', name: 'true', type: 'any', description: 'Path when condition is true' },
      { id: 'false', name: 'false', type: 'any', description: 'Path when condition is false' },
    ],
    hasAI: false,
    color: 'amber',
    icon: 'GitBranch',
    tags: ['condition', 'if', 'branch', 'route'],
    configSchema: {
      fields: [
        { key: 'expression', type: 'string', label: 'Expression', required: true,
          placeholder: 'value === "hello"',
          description: 'JavaScript expression that evaluates to true or false' },
        { key: 'mode', type: 'select', label: 'Evaluation Mode', defaultValue: 'expression',
          options: [
            { label: 'Expression', value: 'expression', description: 'JavaScript expression' },
            { label: 'Equals', value: 'equals', description: 'Simple equality check' },
            { label: 'Contains', value: 'contains', description: 'String contains check' },
            { label: 'Regex', value: 'regex', description: 'Regular expression match' },
          ] },
      ],
    },
  },
  {
    id: 'logic.Switch',
    name: 'logic.Switch',
    displayName: 'Switch',
    version: '1.0.0',
    kind: 'logic',
    category: 'logic',
    description: 'Route to multiple branches based on value matching',
    inputs: [
      { id: 'value', name: 'value', type: 'any', required: true, description: 'Value to match' },
    ],
    outputs: [
      { id: 'case_a', name: 'case_a', type: 'any', description: 'First match path' },
      { id: 'case_b', name: 'case_b', type: 'any', description: 'Second match path' },
      { id: 'default', name: 'default', type: 'any', description: 'Default path' },
    ],
    hasAI: false,
    color: 'amber',
    icon: 'Route',
    tags: ['switch', 'case', 'multi-branch'],
  },
  {
    id: 'logic.Loop',
    name: 'logic.Loop',
    displayName: 'Loop',
    version: '1.0.0',
    kind: 'logic',
    category: 'logic',
    description: 'Iterate over an array, executing the branch for each item',
    inputs: [
      { id: 'items', name: 'items', type: 'any[]', required: true, description: 'Items to iterate' },
    ],
    outputs: [
      { id: 'item', name: 'item', type: 'any', description: 'Current item in iteration' },
      { id: 'done', name: 'done', type: 'any', description: 'Triggered when loop completes' },
    ],
    hasAI: false,
    color: 'amber',
    icon: 'Repeat',
    tags: ['loop', 'iterate', 'for-each'],
  },
  {
    id: 'logic.Parallel',
    name: 'logic.Parallel',
    displayName: 'Parallel',
    version: '1.0.0',
    kind: 'logic',
    category: 'logic',
    description: 'Execute multiple branches simultaneously and wait for all',
    inputs: [
      { id: 'trigger', name: 'trigger', type: 'any', required: true, description: 'Input signal' },
    ],
    outputs: [
      { id: 'branch_1', name: 'branch_1', type: 'any', description: 'First parallel branch' },
      { id: 'branch_2', name: 'branch_2', type: 'any', description: 'Second parallel branch' },
      { id: 'branch_3', name: 'branch_3', type: 'any', description: 'Third parallel branch' },
    ],
    hasAI: false,
    color: 'amber',
    icon: 'GitMerge',
    tags: ['parallel', 'concurrent', 'fan-out'],
  },
  {
    id: 'logic.Merge',
    name: 'logic.Merge',
    displayName: 'Merge',
    version: '1.0.0',
    kind: 'logic',
    category: 'logic',
    description: 'Merge multiple branches back into a single flow',
    inputs: [
      { id: 'branch_1', name: 'branch_1', type: 'any', description: 'First branch input' },
      { id: 'branch_2', name: 'branch_2', type: 'any', description: 'Second branch input' },
      { id: 'branch_3', name: 'branch_3', type: 'any', description: 'Third branch input' },
    ],
    outputs: [
      { id: 'merged', name: 'merged', type: 'any', description: 'Merged output' },
    ],
    hasAI: false,
    color: 'amber',
    icon: 'Merge',
    tags: ['merge', 'join', 'fan-in'],
  },
  {
    id: 'logic.Delay',
    name: 'logic.Delay',
    displayName: 'Delay',
    version: '1.0.0',
    kind: 'logic',
    category: 'logic',
    description: 'Wait for a specified duration before continuing',
    inputs: [
      { id: 'duration', name: 'duration', type: 'number', required: true, description: 'Duration in milliseconds' },
    ],
    outputs: [
      { id: 'pass', name: 'pass', type: 'any', description: 'Continues after delay' },
    ],
    hasAI: false,
    color: 'amber',
    icon: 'Timer',
    tags: ['delay', 'wait', 'sleep'],
  },
  {
    id: 'logic.ErrorHandler',
    name: 'logic.ErrorHandler',
    displayName: 'Error Handler',
    version: '1.0.0',
    kind: 'logic',
    category: 'logic',
    description: 'Catch and handle errors from upstream nodes',
    inputs: [
      { id: 'error', name: 'error', type: 'any', required: true, description: 'Error input' },
    ],
    outputs: [
      { id: 'handled', name: 'handled', type: 'any', description: 'Continue after handling' },
      { id: 'rethrow', name: 'rethrow', type: 'any', description: 'Propagate the error' },
    ],
    hasAI: false,
    color: 'amber',
    icon: 'ShieldAlert',
    tags: ['error', 'catch', 'try', 'handler'],
  },

  // ==================== TRUST & GOVERNANCE (8) ====================
  {
    id: 'trust.HumanApproval',
    name: 'trust.HumanApproval',
    displayName: 'Human Approval',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Pause workflow until a human approves or rejects',
    inputs: [
      { id: 'data', name: 'data', type: 'any', required: true, description: 'Data to review' },
      { id: 'reason', name: 'reason', type: 'string', required: true, description: 'Why approval is needed' },
      { id: 'assignee', name: 'assignee', type: 'string', description: 'Reviewer to assign' },
    ],
    outputs: [
      { id: 'approved', name: 'approved', type: 'any', description: 'Path when approved' },
      { id: 'rejected', name: 'rejected', type: 'any', description: 'Path when rejected' },
      { id: 'notes', name: 'notes', type: 'string', description: 'Reviewer notes' },
    ],
    hasAI: false,
    color: 'rose',
    icon: 'UserCheck',
    tags: ['human', 'approval', 'review', 'gate'],
  },
  {
    id: 'trust.PolicyCheck',
    name: 'trust.PolicyCheck',
    displayName: 'Policy Check',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Evaluate content against configurable policy rules',
    inputs: [
      { id: 'content', name: 'content', type: 'any', required: true, description: 'Content to check' },
      { id: 'policy_id', name: 'policy_id', type: 'string', required: true, description: 'Policy rule set' },
    ],
    outputs: [
      { id: 'pass', name: 'pass', type: 'any', description: 'Content passed policy' },
      { id: 'fail', name: 'fail', type: 'any', description: 'Content failed policy' },
      { id: 'violations', name: 'violations', type: 'string[]', description: 'Policy violations found' },
    ],
    hasAI: false,
    color: 'rose',
    icon: 'ClipboardCheck',
    tags: ['policy', 'compliance', 'rules'],
  },
  {
    id: 'trust.ContentGuardrail',
    name: 'trust.ContentGuardrail',
    displayName: 'Content Guardrail',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Filter AI output for harmful, biased, or off-topic content',
    inputs: [
      { id: 'content', name: 'content', type: 'string', required: true, description: 'AI-generated content' },
      { id: 'rules', name: 'rules', type: 'string[]', description: 'Guardrail rules' },
    ],
    outputs: [
      { id: 'safe', name: 'safe', type: 'string', description: 'Filtered safe content' },
      { id: 'blocked', name: 'blocked', type: 'any', description: 'Triggered if content blocked' },
      { id: 'flags', name: 'flags', type: 'string[]', description: 'Content flags raised' },
    ],
    hasAI: true,
    aiToggles: ['sensitivity_level'],
    color: 'rose',
    icon: 'Shield',
    tags: ['guardrail', 'safety', 'filter', 'moderation'],
    configSchema: {
      groups: [
        { key: 'detection', label: 'Detection', order: 1 },
        { key: 'action', label: 'Actions', order: 2 },
        { key: 'advanced', label: 'Advanced', order: 3, collapsible: true, defaultCollapsed: true },
      ],
      fields: [
        { key: 'sensitivity', type: 'select', label: 'Sensitivity Level', required: true, defaultValue: 'medium',
          options: [
            { label: 'Low', value: 'low', description: 'Only block clearly harmful content' },
            { label: 'Medium', value: 'medium', description: 'Balanced detection' },
            { label: 'High', value: 'high', description: 'Strict filtering' },
          ], group: 'detection' },
        { key: 'categories', type: 'string-array', label: 'Block Categories',
          defaultValue: ['hate_speech', 'violence', 'pii'],
          placeholder: 'e.g. hate_speech', group: 'detection' },
        { key: 'on_block', type: 'select', label: 'When Blocked', defaultValue: 'replace',
          options: [
            { label: 'Replace with message', value: 'replace' },
            { label: 'Stop workflow', value: 'stop' },
            { label: 'Flag and continue', value: 'flag' },
          ], group: 'action' },
        { key: 'replacement_message', type: 'textarea', label: 'Replacement Message',
          defaultValue: 'I cannot provide that response. Let me try a different approach.',
          placeholder: 'Enter replacement text...',
          visibleWhen: [{ field: 'on_block', value: 'replace' }], group: 'action' },
        { key: 'custom_rules', type: 'json', label: 'Custom Rules (JSON)',
          placeholder: '[\n  { "pattern": "...", "action": "block" }\n]',
          validation: { validJson: true }, group: 'advanced' },
      ],
    },
  },
  {
    id: 'trust.PIIRedactor',
    name: 'trust.PIIRedactor',
    displayName: 'PII Redactor',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Detect and redact personally identifiable information from text',
    inputs: [
      { id: 'text', name: 'text', type: 'string', required: true, description: 'Text to redact' },
      { id: 'entity_types', name: 'entity_types', type: 'string[]', description: 'PII types to detect' },
    ],
    outputs: [
      { id: 'redacted', name: 'redacted', type: 'string', description: 'Redacted text' },
      { id: 'entities', name: 'entities', type: 'object[]', description: 'Detected PII entities' },
    ],
    hasAI: true,
    aiToggles: ['detection_model'],
    color: 'rose',
    icon: 'EyeOff',
    tags: ['pii', 'redact', 'privacy', 'gdpr'],
  },
  {
    id: 'trust.InputValidator',
    name: 'trust.InputValidator',
    displayName: 'Input Validator',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Validate and sanitize user inputs against a schema',
    inputs: [
      { id: 'input', name: 'input', type: 'any', required: true, description: 'Input to validate' },
      { id: 'schema', name: 'schema', type: 'object', required: true, description: 'Validation schema' },
    ],
    outputs: [
      { id: 'valid', name: 'valid', type: 'any', description: 'Validated input' },
      { id: 'invalid', name: 'invalid', type: 'any', description: 'Path if validation fails' },
      { id: 'errors', name: 'errors', type: 'string[]', description: 'Validation errors' },
    ],
    hasAI: false,
    color: 'rose',
    icon: 'CheckSquare',
    tags: ['validate', 'sanitize', 'schema'],
  },
  {
    id: 'trust.RateLimiter',
    name: 'trust.RateLimiter',
    displayName: 'Rate Limiter',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Throttle requests to prevent abuse and control costs',
    inputs: [
      { id: 'key', name: 'key', type: 'string', required: true, description: 'Rate limit key (e.g. user_id)' },
      { id: 'limit', name: 'limit', type: 'number', required: true, description: 'Max requests per window' },
      { id: 'window', name: 'window', type: 'number', description: 'Window in seconds' },
    ],
    outputs: [
      { id: 'allowed', name: 'allowed', type: 'any', description: 'Request is within limit' },
      { id: 'throttled', name: 'throttled', type: 'any', description: 'Request exceeds limit' },
      { id: 'remaining', name: 'remaining', type: 'number', description: 'Remaining requests' },
    ],
    hasAI: false,
    color: 'rose',
    icon: 'Gauge',
    tags: ['rate-limit', 'throttle', 'abuse'],
  },
  {
    id: 'trust.AuditLog',
    name: 'trust.AuditLog',
    displayName: 'Audit Log',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Write an immutable audit log entry for compliance and traceability',
    inputs: [
      { id: 'action', name: 'action', type: 'string', required: true, description: 'Action performed' },
      { id: 'data', name: 'data', type: 'any', description: 'Associated data' },
      { id: 'actor', name: 'actor', type: 'string', description: 'Who performed the action' },
    ],
    outputs: [
      { id: 'pass', name: 'pass', type: 'any', description: 'Continues after logging' },
      { id: 'log_id', name: 'log_id', type: 'string', description: 'Audit log entry ID' },
    ],
    hasAI: false,
    color: 'rose',
    icon: 'ScrollText',
    tags: ['audit', 'log', 'compliance', 'trace'],
  },
  {
    id: 'trust.AttestationGate',
    name: 'trust.AttestationGate',
    displayName: 'Attestation Gate',
    version: '1.0.0',
    kind: 'trust',
    category: 'trust',
    description: 'Verify confidential VM attestation before proceeding',
    inputs: [
      { id: 'attestation', name: 'attestation', type: 'object', required: true, description: 'Attestation report' },
      { id: 'policy', name: 'policy', type: 'string', description: 'Expected attestation policy' },
    ],
    outputs: [
      { id: 'verified', name: 'verified', type: 'any', description: 'Attestation verified' },
      { id: 'failed', name: 'failed', type: 'any', description: 'Attestation failed' },
    ],
    hasAI: false,
    color: 'rose',
    icon: 'Fingerprint',
    tags: ['attestation', 'tee', 'confidential', 'verify'],
  },

  // ==================== DATA & TRANSFORM (6) ====================
  {
    id: 'data.Variable',
    name: 'data.Variable',
    displayName: 'Variable',
    version: '1.0.0',
    kind: 'transform',
    category: 'data',
    description: 'Set or get a workflow variable',
    inputs: [
      { id: 'name', name: 'name', type: 'string', required: true, description: 'Variable name' },
      { id: 'value', name: 'value', type: 'any', description: 'Value to set' },
    ],
    outputs: [
      { id: 'value', name: 'value', type: 'any', description: 'Variable value' },
    ],
    hasAI: false,
    color: 'indigo',
    icon: 'Variable',
    tags: ['variable', 'set', 'get', 'state'],
  },
  {
    id: 'data.Code',
    name: 'data.Code',
    displayName: 'Code',
    version: '1.0.0',
    kind: 'transform',
    category: 'data',
    description: 'Execute custom JavaScript/Python code in a sandboxed environment',
    inputs: [
      { id: 'code', name: 'code', type: 'string', required: true, description: 'Code to execute' },
      { id: 'inputs', name: 'inputs', type: 'object', description: 'Input variables' },
    ],
    outputs: [
      { id: 'result', name: 'result', type: 'any', description: 'Execution result' },
      { id: 'logs', name: 'logs', type: 'string[]', description: 'Console output' },
    ],
    hasAI: false,
    color: 'indigo',
    icon: 'Code',
    tags: ['code', 'script', 'javascript', 'python'],
  },
  {
    id: 'data.DataTransform',
    name: 'data.DataTransform',
    displayName: 'Data Transform',
    version: '1.0.0',
    kind: 'transform',
    category: 'data',
    description: 'Transform data using JSONata or mapping expressions',
    inputs: [
      { id: 'input', name: 'input', type: 'any', required: true, description: 'Input data' },
      { id: 'expression', name: 'expression', type: 'string', required: true, description: 'Transform expression' },
    ],
    outputs: [
      { id: 'output', name: 'output', type: 'any', description: 'Transformed data' },
    ],
    hasAI: false,
    color: 'indigo',
    icon: 'Shuffle',
    tags: ['transform', 'map', 'jsonata'],
  },
  {
    id: 'data.Template',
    name: 'data.Template',
    displayName: 'Template',
    version: '1.0.0',
    kind: 'transform',
    category: 'data',
    description: 'Render a text template with variable interpolation',
    inputs: [
      { id: 'template', name: 'template', type: 'string', required: true, description: 'Template string' },
      { id: 'variables', name: 'variables', type: 'object', required: true, description: 'Template variables' },
    ],
    outputs: [
      { id: 'text', name: 'text', type: 'string', description: 'Rendered text' },
    ],
    hasAI: false,
    color: 'indigo',
    icon: 'FileCode',
    tags: ['template', 'render', 'interpolate'],
  },
  {
    id: 'data.Parser',
    name: 'data.Parser',
    displayName: 'Parser',
    version: '1.0.0',
    kind: 'transform',
    category: 'data',
    description: 'Parse structured data from text (JSON, XML, CSV, regex)',
    inputs: [
      { id: 'text', name: 'text', type: 'string', required: true, description: 'Text to parse' },
      { id: 'format', name: 'format', type: 'string', required: true, description: 'Parse format (json, xml, csv, regex)' },
    ],
    outputs: [
      { id: 'data', name: 'data', type: 'any', description: 'Parsed data' },
      { id: 'error', name: 'error', type: 'string', description: 'Parse error if any' },
    ],
    hasAI: false,
    color: 'indigo',
    icon: 'Braces',
    tags: ['parse', 'json', 'xml', 'csv', 'regex'],
  },
  {
    id: 'data.Aggregator',
    name: 'data.Aggregator',
    displayName: 'Aggregator',
    version: '1.0.0',
    kind: 'transform',
    category: 'data',
    description: 'Collect multiple inputs into a single array or object',
    inputs: [
      { id: 'item', name: 'item', type: 'any', required: true, description: 'Item to aggregate' },
      { id: 'key', name: 'key', type: 'string', description: 'Aggregation key' },
    ],
    outputs: [
      { id: 'collection', name: 'collection', type: 'any[]', description: 'Aggregated collection' },
      { id: 'count', name: 'count', type: 'number', description: 'Item count' },
    ],
    hasAI: false,
    color: 'indigo',
    icon: 'Layers',
    tags: ['aggregate', 'collect', 'batch', 'accumulate'],
  },

  // ==================== CONNECTIONS (7) ====================
  {
    id: 'connection.HTTPRequest',
    name: 'connection.HTTPRequest',
    displayName: 'HTTP Request',
    version: '1.0.0',
    kind: 'connection',
    category: 'connections',
    description: 'Make an HTTP request to any external API',
    inputs: [
      { id: 'url', name: 'url', type: 'string', required: true, description: 'Request URL' },
      { id: 'method', name: 'method', type: 'string', required: true, description: 'HTTP method' },
      { id: 'headers', name: 'headers', type: 'object', description: 'Request headers' },
      { id: 'body', name: 'body', type: 'any', description: 'Request body' },
    ],
    outputs: [
      { id: 'response', name: 'response', type: 'any', description: 'Response body' },
      { id: 'status', name: 'status', type: 'number', description: 'HTTP status code' },
      { id: 'headers', name: 'headers', type: 'object', description: 'Response headers' },
    ],
    hasAI: false,
    color: 'green',
    icon: 'Globe',
    tags: ['http', 'api', 'request', 'fetch'],
  },
  {
    id: 'connection.Database',
    name: 'connection.Database',
    displayName: 'Database',
    version: '1.0.0',
    kind: 'connection',
    category: 'connections',
    description: 'Execute a query against a connected database',
    inputs: [
      { id: 'query', name: 'query', type: 'string', required: true, description: 'SQL or query string' },
      { id: 'params', name: 'params', type: 'any[]', description: 'Query parameters' },
    ],
    outputs: [
      { id: 'rows', name: 'rows', type: 'object[]', description: 'Query results' },
      { id: 'affected', name: 'affected', type: 'number', description: 'Rows affected' },
    ],
    hasAI: false,
    color: 'green',
    icon: 'DatabaseZap',
    tags: ['database', 'sql', 'query', 'postgres'],
  },
  {
    id: 'connection.EmailSend',
    name: 'connection.EmailSend',
    displayName: 'Send Email',
    version: '1.0.0',
    kind: 'connection',
    category: 'connections',
    description: 'Send an email via configured SMTP or API provider',
    inputs: [
      { id: 'to', name: 'to', type: 'string', required: true, description: 'Recipient address' },
      { id: 'subject', name: 'subject', type: 'string', required: true, description: 'Email subject' },
      { id: 'body', name: 'body', type: 'string', required: true, description: 'Email body' },
      { id: 'attachments', name: 'attachments', type: 'File[]', description: 'Attachments' },
    ],
    outputs: [
      { id: 'sent', name: 'sent', type: 'boolean', description: 'Send success' },
      { id: 'message_id', name: 'message_id', type: 'string', description: 'Message ID' },
    ],
    hasAI: false,
    color: 'green',
    icon: 'Send',
    tags: ['email', 'send', 'smtp'],
  },
  {
    id: 'connection.Slack',
    name: 'connection.Slack',
    displayName: 'Slack',
    version: '1.0.0',
    kind: 'connection',
    category: 'connections',
    description: 'Send messages to Slack channels or users',
    inputs: [
      { id: 'channel', name: 'channel', type: 'string', required: true, description: 'Channel or user ID' },
      { id: 'message', name: 'message', type: 'string', required: true, description: 'Message text' },
      { id: 'blocks', name: 'blocks', type: 'object[]', description: 'Block Kit blocks' },
    ],
    outputs: [
      { id: 'sent', name: 'sent', type: 'boolean', description: 'Send success' },
      { id: 'ts', name: 'ts', type: 'string', description: 'Message timestamp' },
    ],
    hasAI: false,
    color: 'green',
    icon: 'Hash',
    tags: ['slack', 'message', 'notification'],
  },
  {
    id: 'connection.WebhookOut',
    name: 'connection.WebhookOut',
    displayName: 'Webhook Out',
    version: '1.0.0',
    kind: 'connection',
    category: 'connections',
    description: 'Send a webhook to an external URL',
    inputs: [
      { id: 'url', name: 'url', type: 'string', required: true, description: 'Webhook URL' },
      { id: 'payload', name: 'payload', type: 'object', required: true, description: 'JSON payload' },
    ],
    outputs: [
      { id: 'response', name: 'response', type: 'object', description: 'Response body' },
      { id: 'status', name: 'status', type: 'number', description: 'HTTP status' },
    ],
    hasAI: false,
    color: 'green',
    icon: 'Webhook',
    tags: ['webhook', 'callback', 'notify'],
  },
  {
    id: 'connection.FileStorage',
    name: 'connection.FileStorage',
    displayName: 'File Storage',
    version: '1.0.0',
    kind: 'connection',
    category: 'connections',
    description: 'Read or write files to cloud storage (S3, GCS, etc.)',
    inputs: [
      { id: 'operation', name: 'operation', type: 'string', required: true, description: '"read", "write", or "delete"' },
      { id: 'path', name: 'path', type: 'string', required: true, description: 'Storage path' },
      { id: 'data', name: 'data', type: 'any', description: 'Data to write' },
    ],
    outputs: [
      { id: 'result', name: 'result', type: 'any', description: 'Operation result or file content' },
      { id: 'url', name: 'url', type: 'string', description: 'File URL' },
    ],
    hasAI: false,
    color: 'green',
    icon: 'FolderOpen',
    tags: ['storage', 's3', 'file', 'cloud'],
  },
  {
    id: 'connection.WebSocket',
    name: 'connection.WebSocket',
    displayName: 'WebSocket',
    version: '1.0.0',
    kind: 'connection',
    category: 'connections',
    description: 'Send or receive messages over a WebSocket connection',
    inputs: [
      { id: 'url', name: 'url', type: 'string', required: true, description: 'WebSocket URL' },
      { id: 'message', name: 'message', type: 'any', description: 'Message to send' },
    ],
    outputs: [
      { id: 'message', name: 'message', type: 'any', description: 'Received message' },
      { id: 'connected', name: 'connected', type: 'boolean', description: 'Connection status' },
    ],
    hasAI: false,
    color: 'green',
    icon: 'Radio',
    tags: ['websocket', 'realtime', 'streaming'],
  },

  // ==================== OUTPUTS & RESPONSES (6) ====================
  {
    id: 'output.ChatResponse',
    name: 'output.ChatResponse',
    displayName: 'Chat Response',
    version: '1.0.0',
    kind: 'output',
    category: 'outputs',
    description: 'Send a chat response back to the user',
    inputs: [
      { id: 'message', name: 'message', type: 'string', required: true, description: 'Response message' },
      { id: 'metadata', name: 'metadata', type: 'object', description: 'Response metadata' },
    ],
    outputs: [
      { id: 'sent', name: 'sent', type: 'any', description: 'Continues after sending' },
    ],
    hasAI: false,
    color: 'slate',
    icon: 'MessageCircle',
    tags: ['chat', 'response', 'reply'],
  },
  {
    id: 'output.APIResponse',
    name: 'output.APIResponse',
    displayName: 'API Response',
    version: '1.0.0',
    kind: 'output',
    category: 'outputs',
    description: 'Return a structured API response to the caller',
    inputs: [
      { id: 'body', name: 'body', type: 'any', required: true, description: 'Response body' },
      { id: 'status', name: 'status', type: 'number', description: 'HTTP status code' },
      { id: 'headers', name: 'headers', type: 'object', description: 'Response headers' },
    ],
    outputs: [],
    hasAI: false,
    color: 'slate',
    icon: 'ArrowRightFromLine',
    tags: ['api', 'response', 'return'],
  },
  {
    id: 'output.Notification',
    name: 'output.Notification',
    displayName: 'Notification',
    version: '1.0.0',
    kind: 'output',
    category: 'outputs',
    description: 'Send a push or in-app notification to a user',
    inputs: [
      { id: 'user_id', name: 'user_id', type: 'string', required: true, description: 'Recipient user' },
      { id: 'title', name: 'title', type: 'string', required: true, description: 'Notification title' },
      { id: 'message', name: 'message', type: 'string', required: true, description: 'Notification body' },
    ],
    outputs: [
      { id: 'sent', name: 'sent', type: 'boolean', description: 'Send success' },
    ],
    hasAI: false,
    color: 'slate',
    icon: 'Bell',
    tags: ['notification', 'push', 'alert'],
  },
  {
    id: 'output.Escalation',
    name: 'output.Escalation',
    displayName: 'Escalation',
    version: '1.0.0',
    kind: 'output',
    category: 'outputs',
    description: 'Escalate the conversation to a human agent',
    inputs: [
      { id: 'reason', name: 'reason', type: 'string', required: true, description: 'Escalation reason' },
      { id: 'context', name: 'context', type: 'any', description: 'Conversation context' },
      { id: 'priority', name: 'priority', type: 'string', description: 'Priority level' },
    ],
    outputs: [
      { id: 'escalated', name: 'escalated', type: 'any', description: 'Continues after escalation' },
      { id: 'agent_id', name: 'agent_id', type: 'string', description: 'Assigned human agent' },
    ],
    hasAI: false,
    color: 'slate',
    icon: 'PhoneForwarded',
    tags: ['escalate', 'human', 'handoff', 'transfer'],
  },
  {
    id: 'output.EndSuccess',
    name: 'output.EndSuccess',
    displayName: 'End: Success',
    version: '1.0.0',
    kind: 'output',
    category: 'outputs',
    description: 'Mark the workflow as completed successfully',
    inputs: [
      { id: 'result', name: 'result', type: 'any', description: 'Final result' },
      { id: 'message', name: 'message', type: 'string', description: 'Completion message' },
    ],
    outputs: [],
    hasAI: false,
    color: 'emerald',
    icon: 'CheckCircle',
    tags: ['end', 'success', 'complete'],
  },
  {
    id: 'output.EndError',
    name: 'output.EndError',
    displayName: 'End: Error',
    version: '1.0.0',
    kind: 'output',
    category: 'outputs',
    description: 'Mark the workflow as failed with an error',
    inputs: [
      { id: 'error', name: 'error', type: 'string', required: true, description: 'Error message' },
      { id: 'details', name: 'details', type: 'any', description: 'Error details' },
    ],
    outputs: [],
    hasAI: false,
    color: 'red',
    icon: 'XCircle',
    tags: ['end', 'error', 'fail'],
  },
]

// Helper function to get component by ID
export function getComponentById(id: string): ComponentDefinition | undefined {
  return mockComponents.find(c => c.id === id)
}

// Helper function to get components by category
export function getComponentsByCategory(categoryId: string): ComponentDefinition[] {
  return mockComponents.filter(c => c.category === categoryId)
}

// Helper to get node color class
export function getNodeColorClasses(color: string): { border: string; bg: string; glow: string } {
  const colors: Record<string, { border: string; bg: string; glow: string }> = {
    green: {
      border: 'border-green-400/60',
      bg: 'bg-green-400',
      glow: 'shadow-[0_0_20px_rgba(74,222,128,0.3)] hover:shadow-[0_0_30px_rgba(74,222,128,0.5)]',
    },
    blue: {
      border: 'border-blue-400/60',
      bg: 'bg-blue-400',
      glow: 'shadow-[0_0_20px_rgba(96,165,250,0.3)] hover:shadow-[0_0_30px_rgba(96,165,250,0.5)]',
    },
    purple: {
      border: 'border-purple-400/60',
      bg: 'bg-purple-400',
      glow: 'shadow-[0_0_20px_rgba(192,132,252,0.3)] hover:shadow-[0_0_30px_rgba(192,132,252,0.5)]',
    },
    yellow: {
      border: 'border-yellow-400/60',
      bg: 'bg-yellow-400',
      glow: 'shadow-[0_0_20px_rgba(250,204,21,0.3)] hover:shadow-[0_0_30px_rgba(250,204,21,0.5)]',
    },
    orange: {
      border: 'border-orange-400/60',
      bg: 'bg-orange-400',
      glow: 'shadow-[0_0_20px_rgba(251,146,60,0.3)] hover:shadow-[0_0_30px_rgba(251,146,60,0.5)]',
    },
    cyan: {
      border: 'border-cyan-400/60',
      bg: 'bg-cyan-400',
      glow: 'shadow-[0_0_20px_rgba(34,211,238,0.3)] hover:shadow-[0_0_30px_rgba(34,211,238,0.5)]',
    },
    gray: {
      border: 'border-gray-400/60',
      bg: 'bg-gray-400',
      glow: 'shadow-[0_0_20px_rgba(156,163,175,0.3)] hover:shadow-[0_0_30px_rgba(156,163,175,0.5)]',
    },
    emerald: {
      border: 'border-emerald-400/60',
      bg: 'bg-emerald-400',
      glow: 'shadow-[0_0_20px_rgba(52,211,153,0.3)] hover:shadow-[0_0_30px_rgba(52,211,153,0.5)]',
    },
    red: {
      border: 'border-red-400/60',
      bg: 'bg-red-400',
      glow: 'shadow-[0_0_20px_rgba(248,113,113,0.3)] hover:shadow-[0_0_30px_rgba(248,113,113,0.5)]',
    },
    amber: {
      border: 'border-amber-400/60',
      bg: 'bg-amber-400',
      glow: 'shadow-[0_0_20px_rgba(251,191,36,0.3)] hover:shadow-[0_0_30px_rgba(251,191,36,0.5)]',
    },
    rose: {
      border: 'border-rose-400/60',
      bg: 'bg-rose-400',
      glow: 'shadow-[0_0_20px_rgba(251,113,133,0.3)] hover:shadow-[0_0_30px_rgba(251,113,133,0.5)]',
    },
    indigo: {
      border: 'border-indigo-400/60',
      bg: 'bg-indigo-400',
      glow: 'shadow-[0_0_20px_rgba(129,140,248,0.3)] hover:shadow-[0_0_30px_rgba(129,140,248,0.5)]',
    },
    slate: {
      border: 'border-slate-400/60',
      bg: 'bg-slate-400',
      glow: 'shadow-[0_0_20px_rgba(148,163,184,0.3)] hover:shadow-[0_0_30px_rgba(148,163,184,0.5)]',
    },
  }
  return colors[color] || colors.gray
}
